# Generated by Django 5.2.8 on 2025-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='МГц')),
                ('station', models.CharField(max_length=100, verbose_name='Канал')),
                ('local_station', models.CharField(blank=True, max_length=100, null=True, verbose_name='Местная программа')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('place', models.CharField(blank=True, help_text='Адрес или место установки передатчика и антенны', max_length=200, null=True, verbose_name='Место антенны')),
                ('trp', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Мощность')),
                ('is_works', models.CharField(choices=[('working', 'Работает'), ('temporary_off', 'Временно не работает'), ('planned', 'Планируется'), ('disabled', 'Отключен')], default='planned', max_length=20, verbose_name='Статус передатчика')),
                ('is_rds', models.BooleanField(default=False, verbose_name='Есть RDS?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Данные радиостанции',
                'verbose_name_plural': 'Данные радиостанций',
                'ordering': ['freq'],
                'indexes': [models.Index(fields=['freq'], name='radiostatio_freq_19704a_idx'), models.Index(fields=['city'], name='radiostatio_city_8bfa27_idx'), models.Index(fields=['is_works'], name='radiostatio_is_work_cf3de2_idx')],
            },
        ),
    ]
