# Generated by Django 5.2.8 on 2025-11-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiostations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiodata',
            name='online',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
