# Generated by Django 5.2.8 on 2025-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiostations', '0002_radiodata_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiodata',
            name='detailed_information',
            field=models.TextField(blank=True, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='radiodata',
            name='online',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Онлайн'),
        ),
    ]
