# Generated by Django 5.2.8 on 2025-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiostations', '0003_radiodata_detailed_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiodata',
            name='ant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота установки передатчика'),
        ),
        migrations.AddField(
            model_name='radiodata',
            name='asl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота над уровнем моря'),
        ),
    ]
