# Generated by Django 5.2.8 on 2025-12-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiostations', '0004_radiodata_ant_radiodata_asl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiodata',
            name='freq',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='МГц'),
        ),
        migrations.AlterField(
            model_name='radiodata',
            name='is_works',
            field=models.CharField(choices=[('working', 'Работает'), ('temporary_off', 'Временно не работает'), ('planned', 'Планируется'), ('disabled', 'Отключен'), ('online', 'Онлайн')], default='working', max_length=20, verbose_name='Статус передатчика'),
        ),
        migrations.AlterField(
            model_name='radiodata',
            name='trp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Мощность'),
        ),
    ]
